name: Workflow dispatch URL based on choice example
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the environment to execute test"
        required: true
        default: "test"
        type: "choice"
        options:
          - test
          - sandbox
          - uat
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Set BASE_URL
        shell: bash
        env:
          BASE_URL:
            ${{ github.event.inputs.environment == 'uat' && github.repository.variables.UAT_URL ||
            github.event.inputs.environment == 'test' && github.repository.variables.TEST_URL ||
            github.event.inputs.environment == 'sandbox' && github.repository.variables.SANDBOX_URL }}
        run: |
          echo "The execution was performed on $BASE_URL"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Chromium Browser
        run: npx playwright install chromium
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - name: Displaying the selected option
        run: echo " The execution was performed on $BASE_URL"
